---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager
  namespace: {{ .Values.namespace }}
  labels:
    app: cert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager
  template:
    metadata:
      labels:
        app: cert-manager
    spec:
      serviceAccountName: cert-manager
      containers:
        - name: cert-manager
          image: quay.io/jetstack/cert-manager-controller:v1.15.0
          args:
            - --cluster-resource-namespace=$(POD_NAMESPACE)
            - --leader-election-namespace=$(POD_NAMESPACE)
            - --v=2
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook
  namespace: {{ .Values.namespace }}
  labels:
    app: cert-manager-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager-webhook
  template:
    metadata:
      labels:
        app: cert-manager-webhook
    spec:
      serviceAccountName: cert-manager
      containers:
        - name: cert-manager-webhook
          image: quay.io/jetstack/cert-manager-webhook:v1.15.0
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          volumeMounts:
            - name: webhook-tls
              mountPath: /tls
              readOnly: true
      volumes:
        - name: webhook-tls
          secret:
            secretName: cert-manager-webhook-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-cainjector
  namespace: {{ .Values.namespace }}
  labels:
    app: cert-manager-cainjector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager-cainjector
  template:
    metadata:
      labels:
        app: cert-manager-cainjector
    spec:
      serviceAccountName: cert-manager
      containers:
        - name: cert-manager-cainjector
          image: quay.io/jetstack/cert-manager-cainjector:v1.15.0
---
apiVersion: v1
kind: Service
metadata:
  name: cert-manager
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: cert-manager
  ports:
    - port: 9402
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: cert-manager-webhook
  ports:
    - port: 443
      name: https
---
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-cainjector
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: cert-manager-cainjector
  ports:
    - port: 443
      name: https
---
# ✅ This will issue TLS cert for the webhook service
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-webhook-ca
  namespace: {{ .Values.namespace }}
spec:
  secretName: cert-manager-webhook-tls
  dnsNames:
    - cert-manager-webhook
    - cert-manager-webhook.{{ .Values.namespace }}
    - cert-manager-webhook.{{ .Values.namespace }}.svc
  issuerRef:
    name: mkcert-cluster-issuer
    kind: ClusterIssuer
