metastore:
  database:
    type: postgres
    host: hive-postgres-postgresql.hive-metastore.svc.cluster.local
    port: 5432
    name: metastore
    user: admin
    password: admin

  warehouseDir: s3a://testbuckettrino/testpathtrino

  s3:
    endpoint: http://minio.minio.svc.cluster.local:9000
    accessKey: minioadmin
    secretKey: minioadmin
    pathStyleAccess: true
    sslEnabled: false

service:
  type: ClusterIP
  port: 9083
