image:
  repository: apache/hive
  tag: 3.1.3
  pullPolicy: IfNotPresent

postgres:
  host: postgresql.postgresql.svc.cluster.local
  port: 5432
  db: hive_metastore
  user: admin
  password: admin

metastore:
  port: 9083

resources: {}
