image:
  repository: apache/hive
  tag: 3.1.3

postgres:
  host: postgresql.postgresql.svc.cluster.local
  port: 5432
  database: hive_metastore
  user: admin
  password: admin

warehouseDir: /tmp/hive/warehouse

s3:
  accessKey: minioadmin
  secretKey: minioadmin
  endpoint: http://minio.minio.svc.cluster.local:9000
  sslEnabled: false
