image:
  repository: apache/hive
  tag: 3.1.3

postgres:
  host: postgresql.postgresql.svc.cluster.local
  port: 5432
  database: hive_metastore
  user: admin
  password: admin

warehouseDir: s3a://your-bucket/warehouse

s3:
  endpoint: http://minio.minio.svc.cluster.local:9000
  accessKey: minioadmin
  secretKey: minioadmin
  pathStyleAccess: "true"
  sslEnabled: "false"
