namespace: vault-secrets

serviceAccount:
  create: true
  name: eso

image:
  repository: hashicorp/vault-secrets-operator
  tag: "0.10.0"

vaultConnection:
  name: vault-connection

vaultAuth:
  name: vault-auth
  mount: kubernetes
  role: eso
  serviceAccount: eso
