# Namespace to install into (ArgoCD destination.namespace or helm --namespace)
namespace: vault-secrets

replicaCount: 1

serviceAccount:
  create: true
  name: eso

image:
  repository: hashicorp/vault-secrets-operator
  tag: "0.10.0"
  pullPolicy: IfNotPresent

# VaultConnection / VaultAuth / VaultStaticSecret settings
vault:
  connectionName: vault-connection
  authName: vault-auth

  # KV v2 secrets you want to sync; can list multiple
  staticSecrets:
    - name: airflow-db-secret    # CR name
      mount: kvv2               # engine mount
      path: app-secrets/airflow/db
      destinationName: airflow-db
      refreshAfter: 1m
