replicaCount: 1

image:
  repository: ghcr.io/external-secrets/external-secrets
  tag: v0.18.0

serviceAccount:
  name: eso

vault:
  server: http://vault.vault.svc.cluster.local:8200
  path: kv
  version: v2
  auth:
    mountPath: kubernetes
    role: eso

externalSecret:
  name: airflow-db-creds
  targetSecret: airflow-db
  vaultKey: app-secrets/airflow/db
  properties:
    - secretKey: username
      property: username
    - secretKey: password
      property: password
