replicaCount: 1

image:
  repository: hashicorp/vault-secrets-operator
  tag: 1.12.3

serviceAccount:
  create: true
  name: vso-sa

vault:
  address: http://vault.vault.svc.cluster.local:8200
  skipTLSVerify: true

auth:
  mount: kubernetes   # Vault auth path
  role: eso
  serviceAccount: eso

secret:
  # KV v2 path (without data/) and target K8s Secret
  path: app-secrets/airflow/db
  secretName: airflow-db
  refreshAfter: 1m
