apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: {{ .Values.namespace }}
data:
  config: |
    address-pools:
    - name: {{ .Values.config.addressPool.name }}
      protocol: {{ .Values.config.addressPool.protocol }}
      addresses:
      {{- range .Values.config.addressPool.addresses }}
        - {{ . }}
      {{- end }}
