apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb-controller
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      component: controller
  template:
    metadata:
      labels:
        component: controller
    spec:
      serviceAccountName: metallb-controller
      containers:
        - name: controller
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
          args:
            - controller
            - --webhook-mode=enabled
            - --webhook-secret=metallb-webhook-cert
            - --cert-service-name=metallb-webhook-service
            - --namespace={{ .Values.namespace }}
            - --deployment=metallb-controller
          env:
          - name: METALLB_DISABLE_CRD_WEBHOOK_INJECTION
            value: "true"
          volumeMounts:
            - name: webhook-cert
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
      volumes:
        - name: webhook-cert
          secret:
            secretName: metallb-webhook-cert
            optional: true

---
apiVersion: v1
kind: Service
metadata:
  name: metallb-webhook-service
  namespace: metallb-system
spec:
  selector:
    app: metallb
  ports:
    - name: webhook
      port: 443
      targetPort: webhook
