apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb-controller
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      component: controller
  template:
    metadata:
      labels:
        component: controller
    spec:
      serviceAccountName: metallb-controller
      containers:
        - name: controller
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
          args:
            - controller
            - --webhook-mode=disabled
          env:
            - name: METALLB_DISABLE_CRD_WEBHOOK_INJECTION
              value: "true"
