---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metallb-controller
  namespace: metallb-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metallb-speaker
  namespace: metallb-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metallb-controller
rules:
  # allow writing the webhook cert secret, plus reading services & namespaces
  - apiGroups: [""]
    resources:
      - secrets
      - services
      - services/status       # ← allow patch/update of Service.status
      - namespaces
      - events                # ← allow creating & patching Events
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch

  # full access to MetalLB CRDs and their subresources
  - apiGroups: ["metallb.io"]
    resources: ["*"]
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # manage the validating webhook config
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # allow cert-rotator to tweak the CRD webhook clientConfig
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs:
      - get
      - list
      - watch
      - update
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metallb-speaker
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
      - services
      - endpoints
      - namespaces
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch

  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs:
      - get
      - list
      - watch

  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs:
      - get
      - list
      - watch

  - apiGroups: ["metallb.io"]
    resources:
      - ipaddresspools
      - l2advertisements
      - bgpadvertisements
      - bgppeers
      - bfdprofiles
      - communities
      - servicebgpstatuses
      - servicel2statuses
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metallb-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metallb-controller
subjects:
  - kind: ServiceAccount
    name: metallb-controller
    namespace: metallb-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metallb-speaker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metallb-speaker
subjects:
  - kind: ServiceAccount
    name: metallb-speaker
    namespace: metallb-system
