# 1) The Service pointing at your webhook Deployment
apiVersion: v1
kind: Service
metadata:
  name: metallb-webhook-service
  namespace: metallb-system
spec:
  selector:
    app: metallb
    component: webhook
  ports:
    - name: webhook
      port: 443
      targetPort: 9443

---
# 2) The Deployment running the cert-rotator + webhook server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb-webhook
  namespace: metallb-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metallb
      component: webhook
  template:
    metadata:
      labels:
        app: metallb
        component: webhook
    spec:
      serviceAccountName: metallb-controller
      containers:
      - name: webhook
        image: quay.io/metallb/controller:v0.15.2
        args:
          - webhook
          - --cert-service-name=metallb-webhook-service
          - --webhook-secret=metallb-webhook-cert
          - --namespace=metallb-system
          - --deployment=metallb-webhook
        volumeMounts:
        - name: webhook-cert
          mountPath: /tmp/k8s-webhook-server/serving-certs
      volumes:
      - name: webhook-cert
        secret:
          secretName: metallb-webhook-cert

---
# 3) The ValidatingWebhookConfiguration that wires it all together
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: metallb-webhook-configuration
webhooks:
  - name: validation.metallb.io
    matchPolicy: Equivalent
    admissionReviewVersions: ["v1","v1beta1"]
    sideEffects: None
    rules:
      - apiGroups:   ["metallb.io"]
        apiVersions: ["v1beta1","v1beta2"]
        operations:  ["CREATE","UPDATE"]
        resources:   ["bgppeers","ipaddresspools","l2advertisements","bgpadvertisements","bfdprofiles","communities"]
    clientConfig:
      service:
        namespace: metallb-system
        name: metallb-webhook-service
        path: "/validate"
      caBundle: <base64-encoded-CA-bundle>
