apiVersion: v1
kind: Service
metadata:
  name: metallb-webhook-service
  namespace: metallb-system
spec:
  selector:
    app: metallb
    component: controller
  ports:
    - port: 443
      targetPort: webhook
