apiVersion: v1
kind: Service
metadata:
  name: metallb-webhook-service
  namespace: metallb-system
spec:
  selector:
    app: metallb
  ports:
    - name: webhook
      port: 443
      targetPort: webhook
