apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: metallb-webhook-configuration
webhooks:
  - name: validation.ipaddresspool.metallb.io
    sideEffects: None
    admissionReviewVersions: ["v1"]
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["metallb.io"]
        apiVersions: ["v1beta1"]
        resources: ["ipaddresspools"]
    clientConfig:
      service:
        namespace: metallb-system
        name: metallb-webhook-service
        path: "/validate-metallb-io-v1beta1-ipaddresspool"
        port: 443
      caBundle: {{ .Values.controller.webhook.caBundle | quote }}

  - name: validation.bgppeer.metallb.io
    sideEffects: None
    admissionReviewVersions: ["v1"]
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["metallb.io"]
        apiVersions: ["v1beta2"]
        resources: ["bgppeers"]
    clientConfig:
      service:
        namespace: metallb-system
        name: metallb-webhook-service
        path: "/validate-metallb-io-v1beta2-bgppeer"
        port: 443
      caBundle: {{ .Values.controller.webhook.caBundle | quote }}

  - name: validation.bgpadvertisement.metallb.io
    sideEffects: None
    admissionReviewVersions: ["v1"]
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["metallb.io"]
        apiVersions: ["v1beta1"]
        resources: ["bgpadvertisements"]
    clientConfig:
      service:
        namespace: metallb-system
        name: metallb-webhook-service
        path: "/validate-metallb-io-v1beta1-bgpadvertisement"
        port: 443
      caBundle: {{ .Values.controller.webhook.caBundle | quote }}

  - name: validation.l2advertisement.metallb.io
    sideEffects: None
    admissionReviewVersions: ["v1"]
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["metallb.io"]
        apiVersions: ["v1beta1"]
        resources: ["l2advertisements"]
    clientConfig:
      service:
        namespace: metallb-system
        name: metallb-webhook-service
        path: "/validate-metallb-io-v1beta1-l2advertisement"
        port: 443
      caBundle: {{ .Values.controller.webhook.caBundle | quote }}

  - name: validation.community.metallb.io
    sideEffects: None
    admissionReviewVersions: ["v1"]
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["metallb.io"]
        apiVersions: ["v1beta1"]
        resources: ["communities"]
    clientConfig:
      service:
        namespace: metallb-system
        name: metallb-webhook-service
        path: "/validate-metallb-io-v1beta1-community"
        port: 443
      caBundle: {{ .Values.controller.webhook.caBundle | quote }}

  - name: validation.bfdprofile.metallb.io
    sideEffects: None
    admissionReviewVersions: ["v1"]
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["metallb.io"]
        apiVersions: ["v1beta1"]
        resources: ["bfdprofiles"]
    clientConfig:
      service:
        namespace: metallb-system
        name: metallb-webhook-service
        path: "/validate-metallb-io-v1beta1-bfdprofile"
        port: 443
      caBundle: {{ .Values.controller.webhook.caBundle | quote }}
