apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-core-site
  namespace: {{ .Release.Namespace }}
data:
  core-site.xml: |
    <configuration>
      <property>
        <name>fs.s3a.access.key</name>
        <value>{{ .Values.minio.accessKey }}</value>
      </property>
      <property>
        <name>fs.s3a.secret.key</name>
        <value>{{ .Values.minio.secretKey }}</value>
      </property>
      <property>
        <name>fs.s3a.endpoint</name>
        <value>{{ .Values.minio.endpoint }}</value>
      </property>
      <property>
        <name>fs.s3a.path.style.access</name>
        <value>true</value>
      </property>
      <property>
        <name>fs.s3a.connection.ssl.enabled</name>
        <value>true</value>
      </property>
    </configuration>
