apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino
  namespace: trino
  labels:
    app: trino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino
  template:
    metadata:
      labels:
        app: trino
    spec:
      initContainers:
        - name: init-hive-s3-jars
          image: busybox:1.36
          command:
            - sh
            - -c
            - >
              mkdir -p /plugins/hive-s3 &&
              wget -q -O /plugins/hive-s3/hadoop-aws.jar https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.6/hadoop-aws-3.3.6.jar &&
              wget -q -O /plugins/hive-s3/hadoop-common.jar https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-common/3.3.6/hadoop-common-3.3.6.jar &&
              wget -q -O /plugins/hive-s3/hadoop-auth.jar https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-auth/3.3.6/hadoop-auth-3.3.6.jar &&
              wget -q -O /plugins/hive-s3/aws-java-sdk-bundle.jar https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.1026/aws-java-sdk-bundle-1.11.1026.jar &&
              wget -q -O /plugins/hive-s3/guava.jar https://repo1.maven.org/maven2/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar &&
              wget -q -O /plugins/hive-s3/jsr305.jar https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
          volumeMounts:
            - name: plugin-volume
              mountPath: /plugins

      containers:
        - name: trino
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: trino-config
              mountPath: /etc/trino/config.properties
              subPath: config.properties
            - name: trino-config
              mountPath: /etc/trino/jvm.config
              subPath: jvm.config
            - name: trino-config
              mountPath: /etc/trino/node.properties
              subPath: node.properties
            - name: trino-config
              mountPath: /etc/trino/catalog/hive.properties
              subPath: hive.properties
            - name: plugin-volume
              mountPath: /usr/lib/trino/plugin
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:
        - name: trino-config
          configMap:
            name: trino-config
        - name: plugin-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: trino
  namespace: trino
spec:
  selector:
    app: trino
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 31334
