apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino
  namespace: trino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino
      component: coordinator
  template:
    metadata:
      labels:
        app: trino
        component: coordinator
    spec:
      initContainers:
        - name: init-hadoop-s3-plugin
          image: curlimages/curl:8.4.0
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p /hadoop-s3 && \
              curl -L -o /hadoop-s3/hadoop-aws.jar https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.6/hadoop-aws-3.3.6.jar && \
              curl -L -o /hadoop-s3/aws-java-sdk-bundle.jar https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar
          volumeMounts:
            - name: hadoop-s3-plugin
              mountPath: /hadoop-s3
      containers:
        - name: trino
          image: "trinodb/trino:476"
          imagePullPolicy: IfNotPresent
          command: ["/usr/lib/trino/bin/launcher"]
          args: ["run"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: trino-config
              mountPath: /usr/lib/trino/etc/config.properties
              subPath: config.properties
            - name: trino-config
              mountPath: /usr/lib/trino/etc/jvm.config
              subPath: jvm.config
            - name: trino-config
              mountPath: /usr/lib/trino/etc/node.properties
              subPath: node.properties
            - name: trino-hive-catalog
              mountPath: /usr/lib/trino/etc/catalog/hive.properties
              subPath: hive.properties
            - name: hadoop-s3-plugin
              mountPath: /usr/lib/trino/plugin/hadoop-s3
      volumes:
        - name: trino-config
          configMap:
            name: trino-config
        - name: trino-hive-catalog
          configMap:
            name: trino-hive-catalog
        - name: hadoop-s3-plugin
          emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-worker
  namespace: trino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino
      component: worker
  template:
    metadata:
      labels:
        app: trino
        component: worker
    spec:
      initContainers:
        - name: init-hadoop-s3-plugin
          image: curlimages/curl:8.4.0
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p /hadoop-s3 && \
              curl -L -o /hadoop-s3/hadoop-aws.jar https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.6/hadoop-aws-3.3.6.jar && \
              curl -L -o /hadoop-s3/aws-java-sdk-bundle.jar https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar
          volumeMounts:
            - name: hadoop-s3-plugin
              mountPath: /hadoop-s3
      containers:
        - name: trino
          image: "trinodb/trino:476"
          imagePullPolicy: IfNotPresent
          command: ["/usr/lib/trino/bin/launcher"]
          args: ["run"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: trino-config
              mountPath: /usr/lib/trino/etc/config.properties
              subPath: config.properties
            - name: trino-config
              mountPath: /usr/lib/trino/etc/jvm.config
              subPath: jvm.config
            - name: trino-config
              mountPath: /usr/lib/trino/etc/node.properties
              subPath: node.properties
            - name: trino-hive-catalog
              mountPath: /usr/lib/trino/etc/catalog/hive.properties
              subPath: hive.properties
            - name: hadoop-s3-plugin
              mountPath: /usr/lib/trino/plugin/hadoop-s3
      volumes:
        - name: trino-config
          configMap:
            name: trino-config-worker
        - name: trino-hive-catalog
          configMap:
            name: trino-hive-catalog
        - name: hadoop-s3-plugin
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: trino
  namespace: trino
spec:
  selector:
    app: trino
    component: coordinator
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 31334
