apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino
  namespace: trino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino
      component: coordinator
  template:
    metadata:
      labels:
        app: trino
        component: coordinator
    spec:
      initContainers:
        - name: download-s3-jars
          image: curlimages/curl:8.6.0
          command:
            - sh
            - -c
            - |
              mkdir -p /jars && \
              curl -sSL -o /jars/hadoop-aws.jar https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.6/hadoop-aws-3.3.6.jar && \
              curl -sSL -o /jars/aws-sdk-bundle.jar https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.1026/aws-java-sdk-bundle-1.11.1026.jar
          volumeMounts:
            - name: hadoop-s3a-jars
              mountPath: /jars
      containers:
        - name: trino
          image: "trinodb/trino:476"
          imagePullPolicy: IfNotPresent
          command: ["/usr/lib/trino/bin/launcher"]
          args: ["run"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: trino-config
              mountPath: /usr/lib/trino/etc/config.properties
              subPath: config.properties
            - name: trino-config
              mountPath: /usr/lib/trino/etc/jvm.config
              subPath: jvm.config
            - name: trino-config
              mountPath: /usr/lib/trino/etc/node.properties
              subPath: node.properties
            - name: trino-config
              mountPath: /usr/lib/trino/etc/catalog/hive.properties
              subPath: hive.properties
            - name: hadoop-s3a-jars
              mountPath: /usr/lib/trino/lib/hadoop-extra/
      volumes:
        - name: trino-config
          configMap:
            name: trino-config
        - name: hadoop-s3a-jars
          emptyDir: {}




---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-worker
  namespace: trino
  labels:
    app: trino
    component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino
      component: worker
  template:
    metadata:
      labels:
        app: trino
        component: worker
    spec:
      initContainers:
        - name: download-s3-jars
          image: curlimages/curl:8.6.0
          command:
            - sh
            - -c
            - |
              mkdir -p /jars && \
              curl -sSL -o /jars/hadoop-aws.jar https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.6/hadoop-aws-3.3.6.jar && \
              curl -sSL -o /jars/aws-sdk-bundle.jar https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.1026/aws-java-sdk-bundle-1.11.1026.jar
          volumeMounts:
            - name: hadoop-s3a-jars
              mountPath: /jars
      containers:
        - name: trino
          image: "trinodb/trino:476"
          imagePullPolicy: IfNotPresent
          command: ["/usr/lib/trino/bin/launcher"]
          args: ["run"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: trino-config
              mountPath: /usr/lib/trino/etc/config.properties
              subPath: config.properties
            - name: trino-config
              mountPath: /usr/lib/trino/etc/jvm.config
              subPath: jvm.config
            - name: trino-config
              mountPath: /usr/lib/trino/etc/node.properties
              subPath: node.properties
            - name: trino-config
              mountPath: /usr/lib/trino/etc/catalog/hive.properties
              subPath: hive.properties
            - name: hadoop-s3a-jars
              mountPath: /usr/lib/trino/lib/hadoop-extra/
      volumes:
        - name: trino-config
          configMap:
            name: trino-config-worker
        - name: hadoop-s3a-jars
          emptyDir: {}


---
apiVersion: v1
kind: Service
metadata:
  name: trino
  namespace: trino
spec:
  selector:
    app: trino
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 31334
