apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino
  namespace: trino
  labels:
    app: trino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino
  template:
    metadata:
      labels:
        app: trino
    spec:
      initContainers:
        - name: init-hive-jars
          image: busybox:1.36
          command:
            - sh
            - -c
            - >
              mkdir -p /jars &&
              wget -q -O /jars/hadoop-aws.jar https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar &&
              wget -q -O /jars/aws-java-sdk-bundle.jar https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.1026/aws-java-sdk-bundle-1.11.1026.jar
          volumeMounts:
            - name: hive-jars
              mountPath: /jars

      containers:
        - name: trino
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: trino-config
              mountPath: /etc/trino/config.properties
              subPath: config.properties
            - name: trino-config
              mountPath: /etc/trino/jvm.config
              subPath: jvm.config
            - name: trino-config
              mountPath: /etc/trino/node.properties
              subPath: node.properties
            - name: trino-config
              mountPath: /etc/trino/catalog/hive.properties
              subPath: hive.properties
            - name: hive-jars
              mountPath: /usr/lib/trino/plugin/hive-hadoop2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:
        - name: trino-config
          configMap:
            name: trino-config
        - name: hive-jars
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: trino
  namespace: trino
spec:
  selector:
    app: trino
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 31334 
