apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.controller.ingressClass }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: "{{ .Values.controller.ingressClassDefault }}"
spec:
  controller: k8s.io/ingress-nginx
