apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-controller
  labels:
    app.kubernetes.io/name: ingress-nginx
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  serviceAccountName: ingress-nginx-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingress-nginx
    spec:
      hostNetwork: {{ .Values.controller.hostNetwork }}
      containers:
        - name: controller
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          args:
            - /nginx-ingress-controller
            - --ingress-class={{ .Values.controller.ingressClass }}
            - --default-backend-service={{ .Release.Namespace }}/default-backend
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: {{ .Values.controller.service.httpPort }}
    - name: https
      port: 443
      targetPort: https
      nodePort: {{ .Values.controller.service.httpsPort }}
