namespace: metallb-system

controller:
  image: ghcr.io/metallb/speaker:v0.13.12
  replicas: 1

speaker:
  image: ghcr.io/metallb/speaker:v0.13.12

config:
  addressPool:
    name: default
    protocol: layer2
    addresses:
      - 192.168.1.200-192.168.1.202
