apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      version: "{{ .Values.vault.version }}"
      path: {{ .Values.vault.path | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.vault.auth.mountPath | quote }}
          role: {{ .Values.vault.auth.role | quote }}
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name | quote }}
            namespace: {{ .Release.Namespace | quote }}
            key: token
