apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200   # your Vault HTTP address
      version: v2                                        # KV engine version
      path: kv                                           # mount path of your KV engine
      auth:
        kubernetes:
          mountPath: kubernetes       # the path where you enabled Kubernetes auth in Vault
          role: eso                   # the Vault role you created that binds to your ServiceAccount
          serviceAccountRef:
            # this is the SA that the ESO controller pod uses
            name: eso
            key: token        
