apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-cluster-store
spec:
  provider:
    vault:
      server: {{ .Values.vault.address }}
      path: {{ .Values.vault.path }}
      version: v2
      auth:
        tokenSecretRef:
          name: my-secret
          namespace: {{ .Values.namespace }}
          key: token
