apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      version: v2
      path: kv
      auth:
        kubernetes:
          mountPath: kubernetes      # how you enabled k8s auth in Vault
          role: eso                  # the Vault role you created for this SA
          serviceAccountRef:
            name: eso
            namespace: external-secrets
            key: token
