apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault-connection
  namespace: {{ .Release.Namespace }}
spec:
  address: {{ .Values.vault.address | quote }}
  skipTLSVerify: {{ .Values.vault.skipTLSVerify }}
