apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-secrets-operator
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-secrets-operator
  template:
    metadata:
      labels:
        app: vault-secrets-operator
    spec:
      serviceAccountName: {{ .Values.vaultAuth.serviceAccount }}
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          args:
            - "--metrics-bind-address=:8080"
            - "--health-probe-bind-address=:8081"
            - "--leader-elect"
          ports:
            - containerPort: 8080
              name: metrics
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
