apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-secrets
  template:
    metadata:
      labels:
        app: external-secrets
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: external-secrets
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          args:
            - "--loglevel=info"
            - "--metrics-addr=:8080"
            - "--namespace={{ .Values.namespace }}"
            - "--watch-namespace=*"
            # Uncomment below if you want to enable Vault token cache
            # - "--experimental-enable-vault-token-cache"
          ports:
            - name: metrics
              containerPort: 8080
