apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-cluster-role
rules:
  - apiGroups: [""]
    resources: ["secrets", "namespaces"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["external-secrets.io"]
    resources:
      - "externalsecrets"
      - "pushsecrets"
      - "clusterpushsecrets"
      - "clusterexternalsecrets"
      - "clustersecretstores"
      - "secretstores"
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["generators.external-secrets.io"]
    resources:
      - "generatorstates"
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: eso
    namespace: external-secrets
roleRef:
  kind: ClusterRole
  name: external-secrets-cluster-role
  apiGroup: rbac.authorization.k8s.io
