apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vso-controller-role
rules:
  - apiGroups: ["", "secrets.hashicorp.com"]
    resources: ["pods","secrets","vaultconnections","vaultauths","vaultstaticsecrets","vaultdynamicsecrets","vaultpkisecrets","hcpauths"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles","rolebindings"]
    verbs: ["get","list","watch","create","update","patch","delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vso-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vso-controller-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.namespace }}
