# ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-controller
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "serviceaccounts", "namespaces","events"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["external-secrets.io"]
    resources:
      - "externalsecrets"
      - "externalsecrets/status"
      - "secretstores"
      - "secretstores/status"
      - "clustersecretstores"
      - "clustersecretstores/status"
      - "clusterexternalsecrets"
      - "clusterexternalsecrets/status"
      - "clusterpushsecrets"
      - "clusterpushsecrets/status"
      - "pushsecrets"
      - "pushsecrets/status"
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["generators.external-secrets.io"]
    resources:
      - "*"
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-secrets-controller
subjects:
  - kind: ServiceAccount
    name: eso
    namespace: external-secrets
