apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-cluster-role
rules:
  # Core secrets and namespace access
  - apiGroups: [""]
    resources: ["secrets", "namespaces"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Allow ESO to emit events (used for status updates and errors)
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]

  # External Secrets main API group
  - apiGroups: ["external-secrets.io"]
    resources:
      - "externalsecrets"
      - "externalsecrets/status"
      - "pushsecrets"
      - "pushsecrets/status"
      - "clusterpushsecrets"
      - "clusterpushsecrets/status"
      - "clusterexternalsecrets"
      - "clusterexternalsecrets/status"
      - "secretstores"
      - "clustersecretstores"
      - "clustersecretstores/status"
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Generator controller support
  - apiGroups: ["generators.external-secrets.io"]
    resources:
      - "generatorstates"
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: eso
    namespace: external-secrets
roleRef:
  kind: ClusterRole
  name: external-secrets-cluster-role
  apiGroup: rbac.authorization.k8s.io
