apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vso-controller
rules:
  - apiGroups: [""]
    resources: ["secrets", "serviceaccounts", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["secrets.hashicorp.com"]
    resources: ["vaultconnections", "vaultauths", "vaultstaticsecrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
# templates/02-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vso-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vso-controller
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
