apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vso-controller-role
rules:
  # existing core & VSO rules…
  - apiGroups: ["", "secrets.hashicorp.com"]
    resources:
      - pods
      - secrets
      - vaultconnections
      - vaultauths
      - vaultstaticsecrets
      - vaultdynamicsecrets
      - vaultpkisecrets
      - hcpauths
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection

  # RBAC for roles & bindings
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # <<< ADD THIS NEW BLOCK >>>
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vso-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vso-controller-role
subjects:
  - kind: ServiceAccount
    name: eso
    namespace: vault-secrets
