apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceAccount.name }}-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceAccount.name }}
type: kubernetes.io/service-account-token
