apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: {{ .Release.Namespace }}
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: {{ .Values.auth.mount }}
  kubernetes:
    role: {{ .Values.auth.role }}
    serviceAccount: {{ .Values.auth.serviceAccount }}
