{{- range .Values.vault.staticSecrets }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  vaultAuthRef: {{ $.Values.vault.authName }}
  mount: {{ .mount }}
  path: {{ .path }}
  refreshAfter: {{ .refreshAfter }}
  destination:
    create: true
    name: {{ .destinationName }}
---
{{- end }}
