controller:
  ingressClass: nginx
  ingressClassDefault: true

  replicaCount: 1
  image:
    repository: k8s.gcr.io/ingress-nginx/controller
    tag: v1.13.0
    pullPolicy: IfNotPresent

  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

  service:
    enabled: true
    type: ClusterIP
    ports:
      http: 80
      https: 443

defaultBackend:
  enabled: true
  image:
    repository: k8s.gcr.io/defaultbackend-amd64
    tag: "1.5"
