# ----------------------------------------------------------
# ConfigMap: Pod Template for KubernetesExecutor Worker Pods
# ----------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-pod-template  # Name of the ConfigMap
  namespace: {{ .Values.namespace }}  # Namespace defined in Helm values
data:
  pod_template.yaml: |+
    {{ .Files.Get "config/pod_template.yaml" | nindent 4 }}

