# ----------------------------------------------------------
# ConfigMap: Pod Template for KubernetesExecutor Worker Pods
# ----------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-pod-template  # Name of the ConfigMap
  namespace: {{ .Values.namespace }}  # Namespace defined in Helm values
data:
  pod_template.yaml: |     # This line loads the external pod template file from the Helm chart's config directory.
    {{ .Files.Get "config/pod_template.yaml" | indent 4 }}

