# ------------------------------------------
# PostgreSQL Deployment for Airflow Metadata DB
# ------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-postgresql  # Name of the Deployment
  namespace: {{ .Values.namespace }}  # Namespace from Helm values
spec:
  replicas: 1  # Single replica (PostgreSQL is stateful, so scaling must be handled carefully)
  selector:
    matchLabels:
      app: postgres  # Selector label for matching pods
  template:
    metadata:
      labels:
        app: postgres  # Label for identifying the pod
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine  # Lightweight PostgreSQL 15 image
        env:
        # Set PostgreSQL environment variables from secrets synced via ExternalSecret
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: airflow-db-secret
              key: db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: airflow-db-secret
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: airflow-db-secret
              key: password
        ports:
        - containerPort: 5432  # Default PostgreSQL port exposed inside the pod

        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data  # Mount location for PostgreSQL data directory

      volumes:
      - name: postgres-data
        emptyDir: {}  # Use ephemeral storage (data will be lost on pod restart — not suitable for production)

---
# ------------------------------------------
# PostgreSQL Service (Internal Access)
# ------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: postgres-postgresql
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP  # Default internal service type
  ports:
  - port: 5432  # Service port
    targetPort: 5432  # Port on the PostgreSQL container
  selector:
    app: postgres  # Selects the pod created by the Deployment above

