apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-db-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: airflow-db-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: db
      remoteRef:
        key: app-secrets/airflow/db
        property: db
    - secretKey: user
      remoteRef:
        key: app-secrets/airflow/db
        property: user
    - secretKey: password
      remoteRef:
        key: app-secrets/airflow/db
        property: password
    - secretKey: sql_alchemy_conn
      remoteRef:
        key: app-secrets/airflow/db
        property: sql_alchemy_conn
    - secretKey: webuser
      remoteRef:
        key: app-secrets/airflow/db
        property: webuser
    - secretKey: webpassword
      remoteRef:
        key: app-secrets/airflow/db
        property: webpassword
    - secretKey: webuseremail
      remoteRef:
        key: app-secrets/airflow/db
        property: webuseremail
    - secretKey: webuserfirstname
      remoteRef:
        key: app-secrets/airflow/db
        property: webuserfirstname
    - secretKey: webuserlastname
      remoteRef:
        key: app-secrets/airflow/db
        property: webuserlastname
    - secretKey: secretKey
      remoteRef:
        key: app-secrets/airflow/secret
        property: secretKey   
    - secretKey: fernetKey
      remoteRef:
        key: app-secrets/airflow/secret
        property: fernetKey
