# external-secret-db.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-db-creds
  namespace: airflow
spec:
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    name: airflow-db      # ← this will be the Kubernetes Secret you consume
    creationPolicy: Owner # deletes the Secret when the ExternalSecret is removed
  data:
    - secretKey: username
      remoteRef:
        key: app-secrets/airflow/db
        property: username
    - secretKey: password
      remoteRef:
        key: app-secrets/airflow/db
        property: password
