apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-db-secret
  namespace: airflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: airflow-db-secret
    creationPolicy: Owner
  data:
    - secretKey: db
      remoteRef:
        key: kv/data/app-secrets/airflow/db
        property: db
    - secretKey: user
      remoteRef:
        key: kv/data/app-secrets/airflow/db
        property: user
    - secretKey: password
      remoteRef:
        key: kv/data/app-secrets/airflow/db
        property: password
    - secretKey: sql_alchemy_conn
      remoteRef:
        key: kv/data/app-secrets/airflow/db
        property: sql_alchemy_conn
