apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-db-secret
  namespace: airflow
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: airflow-db-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: kv/airflow/db
        property: username
    - secretKey: password
      remoteRef:
        key: kv/airflow/db
        property: password
