apiVersion: v1 # Used to share logs between components of airflow
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce # Only one pod/node can write to it at a time
  resources:
    requests:
      storage: 1Gi # Allocate 1Gi of storage
  storageClassName: local-path # Use the "local-path" provisioner

