# ---------------------------------------------------------
# Kubernetes Role for Airflow KubernetesExecutor Permissions
# ---------------------------------------------------------
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-k8s-executor-role  # Name of the role
  namespace: {{ .Values.namespace }}  # Namespace-scoped role from Helm values
rules:
  # Permissions on core Kubernetes resources like pods and logs
  - apiGroups: [""]  # "" = core API group
    resources: ["pods", "pods/log", "pods/exec"]  # Resources Airflow workers interact with
    verbs: ["create", "delete", "get", "list", "watch"]  # Required to launch, monitor, and cleanup pods

  # Permissions on Jobs
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["create", "delete", "get", "list", "watch"]

---

# ---------------------------------------------------------
# RoleBinding: Attach the Above Role to the Airflow ServiceAccount
# ---------------------------------------------------------
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-k8s-executor-binding  # Name of the binding
  namespace: {{ .Values.namespace }}  # Same namespace scope
subjects:
  - kind: ServiceAccount
    name: {{ .Values.airflow.serviceAccountName }}  # Bind the role to this Airflow ServiceAccount
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: airflow-k8s-executor-role  # Reference the role defined above
  apiGroup: rbac.authorization.k8s.io  # API group for RBAC
