apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      serviceAccountName: {{ .Values.airflow.serviceAccountName }}
      containers:
      - name: scheduler
        image: "{{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}"
        command: ["/bin/bash", "-c"]
        args:
          - |
            until pg_isready -h postgres-postgresql.airflow.svc.cluster.local -p 5432; do
                echo "Waiting for Postgres to be ready...";
                sleep 5;
            done;
            exec airflow scheduler
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: {{ .Values.airflow.executor }}
        - name: AIRFLOW__KUBERNETES_EXECUTOR__NAMESPACE
          value: {{ .Values.namespace }}
        - name: AIRFLOW__KUBERNETES_EXECUTOR__POD_TEMPLATE_FILE
          value: "/opt/airflow/pod_templates/pod_template.yaml"
        - name: AIRFLOW__CORE__FERNET_KEY
          value: {{ .Values.airflow.fernetKey }}
        - name: AIRFLOW__WEBSERVER__SECRET_KEY
          value: {{ .Values.airflow.secretKey }}
        - name: AIRFLOW__CORE__DAGS_FOLDER
          value: /opt/airflow/dags
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: postgresql+psycopg2://{{ .Values.database.postgres.user }}:{{ .Values.database.postgres.password }}@postgres-postgresql.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.database.postgres.port }}/{{ .Values.database.postgres.db }}
        volumeMounts:
        - name: pod-template-volume
          mountPath: /opt/airflow/pod_templates
        - name: logs-volume
          mountPath: /opt/airflow/logs
        - name: shared-volume
          mountPath: /opt/airflow/shared

      volumes:
      - name: pod-template-volume
        configMap:
          name: airflow-pod-template
          items:
            - key: pod_template.yaml
              path: pod_template.yaml
      - name: logs-volume
        persistentVolumeClaim:
          claimName: airflow-logs-pvc
      - name: shared-volume
        persistentVolumeClaim:
          claimName: airflow-shared-pvc
