apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: airflow
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      version: v2
      path: kv
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eso
          serviceAccountRef:
            name: eso
            namespace: airflow
            key: token
