apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-triggerer
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.triggerer.replicas }}
  selector:
    matchLabels:
      app: airflow-triggerer
  template:
    metadata:
      labels:
        app: airflow-triggerer
    spec:
      serviceAccountName: {{ .Values.airflow.serviceAccountName }}
      containers:
      - name: triggerer
        image: "{{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}"
        command: ["/bin/bash", "-c"]
        args:
          - |
            until pg_isready -h postgres-postgresql.airflow.svc.cluster.local -p 5432; do
              echo "Waiting for Postgres to be ready...";
              sleep 10;
            done;

            # Wait until the metadata database is initialized (e.g., ab_user table exists)
            until psql -h postgres-postgresql.airflow.svc.cluster.local -U airflow -d airflow_db -c '\dt' | grep -q 'ab_user'; do
              echo "Waiting for Airflow metadata DB to be initialized...";
              sleep 5;
            done;

            exec airflow triggerer

        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: {{ .Values.airflow.executor }}
        - name: AIRFLOW__KUBERNETES_EXECUTOR__NAMESPACE
          value: {{ .Values.namespace }}
        - name: AIRFLOW__CORE__FERNET_KEY
          value: {{ .Values.airflow.fernetKey }}
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              name: airflow-db-secret
              key: sql_alchemy_conn
