apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-metastore-site
  namespace: {{ .Release.Namespace }}
data:
  metastore-site.xml: |
    <configuration>
      <!-- DB -->
      <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:postgresql://{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.postgresql.Driver</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>{{ .Values.postgres.user }}</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>{{ .Values.postgres.password }}</value>
      </property>

      <!-- S3 -->
      <property>
        <name>fs.s3a.access.key</name>
        <value>{{ .Values.s3.accessKey }}</value>
      </property>
      <property>
        <name>fs.s3a.secret.key</name>
        <value>{{ .Values.s3.secretKey }}</value>
      </property>
      <property>
        <name>fs.s3a.endpoint</name>
        <value>{{ .Values.s3.endpoint }}</value>
      </property>
      <property>
        <name>fs.s3a.path.style.access</name>
        <value>{{ .Values.s3.pathStyleAccess }}</value>
      </property>
      <property>
        <name>fs.s3a.connection.ssl.enabled</name>
        <value>{{ .Values.s3.sslEnabled }}</value>
      </property>

      <property>
        <name>hive.metastore.warehouse.dir</name>
        <value>{{ .Values.warehouseDir }}</value>
      </property>

      <property>
        <name>hive.execution.engine</name>
        <value>mr</value>
      </property>
    </configuration>
