apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-metastore-site
  namespace: hive-metastore
data:
  metastore-site.xml: |
    <configuration>
      <!-- JDBC + JDO configuration -->
      <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:postgresql://postgresql.postgresql.svc.cluster.local:5432/hive_metastore</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.postgresql.Driver</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>admin</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>admin</value>
      </property>

      <!-- Schema & warehouse -->
      <property>
        <name>datanucleus.autoCreateSchema</name>
        <value>false</value>
      </property>
      <property>
        <name>hive.metastore.warehouse.dir</name>
        <value>s3a://testbuckettrino/testpathtrino</value>
      </property>

      <!-- S3 support -->
      <property>
        <name>fs.s3a.access.key</name>
        <value>minioadmin</value>
      </property>
      <property>
        <name>fs.s3a.secret.key</name>
        <value>minioadmin</value>
      </property>
      <property>
        <name>fs.s3a.endpoint</name>
        <value>http://minio.minio.svc.cluster.local:9000</value>
      </property>
      <property>
        <name>fs.s3a.path.style.access</name>
        <value>true</value>
      </property>
      <property>
        <name>fs.s3a.connection.ssl.enabled</name>
        <value>false</value>
      </property>

      <!-- Disable Tez and use MR engine -->
      <property>
        <name>hive.execution.engine</name>
        <value>mr</value>
      </property>
    </configuration>
