apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-metastore-site
  namespace: {{ .Release.Namespace }}
data:
  metastore-site.xml: |
    <configuration>
      <!-- PostgreSQL Metastore DB -->
      <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:postgresql://{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.postgresql.Driver</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>{{ .Values.postgres.user }}</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>{{ .Values.postgres.password }}</value>
      </property>

      <!-- Dummy warehouse location; not used directly -->
      <property>
        <name>hive.metastore.warehouse.dir</name>
        <value>{{ .Values.warehouseDir }}</value>
      </property>

      <!-- Use MapReduce to avoid Spark dependency -->
      <property>
        <name>hive.execution.engine</name>
        <value>mr</value>
      </property>
    </configuration>

