apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-metastore-site
  namespace: hive-metastore
data:
  metastore-site.xml: |
    <configuration>
      <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:postgresql://{{ .Values.metastore.database.host }}:{{ .Values.metastore.database.port }}/{{ .Values.metastore.database.name }}</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.postgresql.Driver</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>{{ .Values.metastore.database.user }}</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>{{ .Values.metastore.database.password }}</value>
      </property>
      <property>
        <name>datanucleus.autoCreateSchema</name>
        <value>false</value>
      </property>
      <property>
        <name>hive.metastore.warehouse.dir</name>
        <value>{{ .Values.metastore.warehouseDir }}</value>
      </property>
      <property>
        <name>fs.s3a.access.key</name>
        <value>{{ .Values.metastore.s3.accessKey }}</value>
      </property>
      <property>
        <name>fs.s3a.secret.key</name>
        <value>{{ .Values.metastore.s3.secretKey }}</value>
      </property>
      <property>
        <name>fs.s3a.endpoint</name>
        <value>{{ .Values.metastore.s3.endpoint }}</value>
      </property>
      <property>
        <name>fs.s3a.path.style.access</name>
        <value>{{ .Values.metastore.s3.pathStyleAccess }}</value>
      </property>
      <property>
        <name>fs.s3a.connection.ssl.enabled</name>
        <value>{{ .Values.metastore.s3.sslEnabled }}</value>
      </property>
    </configuration>
