apiVersion: batch/v1
kind: Job
metadata:
  name: hive-init-schema
  namespace: hive-metastore
spec:
  template:
    spec:
      containers:
        - name: init-schema
          image: apache/hive:3.1.3
          command:
            - "/opt/hive/bin/schematool"
            - "-initSchema"
            - "-dbType"
            - "postgres"
            - "-verbose"
          env:
            - name: HIVE_CONF_DIR
              value: /opt/hive/conf
          volumeMounts:
            - name: hive-metastore-site
              mountPath: /opt/hive/conf/metastore-site.xml
              subPath: metastore-site.xml
            - name: hive-metastore-site
              mountPath: /opt/hive/conf/hive-site.xml
              subPath: metastore-site.xml
      volumes:
        - name: hive-metastore-site
          configMap:
            name: hive-metastore-site
      restartPolicy: Never
  backoffLimit: 1
