apiVersion: batch/v1
kind: Job
metadata:
  name: hive-init-schema
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-schema
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
            - "/opt/hive/bin/schematool"
            - "-initSchema"
            - "-dbType"
            - "postgres"
            - "-verbose"
          env:
            - name: HIVE_CONF_DIR
              value: /opt/hive/conf
          volumeMounts:
            - name: hive-conf
              mountPath: /opt/hive/conf/metastore-site.xml
              subPath: metastore-site.xml
            - name: hive-conf
              mountPath: /opt/hive/conf/hive-site.xml
              subPath: metastore-site.xml
      volumes:
        - name: hive-conf
          configMap:
            name: hive-metastore-site
