apiVersion: batch/v1
kind: Job
metadata:
  name: hive-init-schema
  namespace: hive-metastore
spec:
  template:
    spec:
      containers:
        - name: init-schema
          image: apache/hive:3.1.3
          command:
            - "/opt/hive/bin/schematool"
            - "-initSchema"
            - "-dbType"
            - "postgres"
            - "-verbose"
            - "-userName"
            - "admin"
            - "-passWord"
            - "admin"
            - "-url"
            - "jdbc:postgresql://postgresql.postgresql.svc.cluster.local:5432/hive_metastore"
      restartPolicy: Never
  backoffLimit: 1
