apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
        - name: metastore
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          args:
            - "--service"
            - "metastore"
          ports:
            - containerPort: 9083
          volumeMounts:
            - name: hive-conf
              mountPath: /opt/hive/conf/metastore-site.xml
              subPath: metastore-site.xml
            - name: hive-conf
              mountPath: /opt/hive/conf/hive-site.xml
              subPath: metastore-site.xml
      volumes:
        - name: hive-conf
          configMap:
            name: hive-metastore-site


---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: hive-metastore
  ports:
    - name: thrift
      port: 9083
      targetPort: 9083
