apiVersion: v1
kind: Namespace
metadata:
  name: hive-metastore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      initContainers:
        # 1) Provide S3A jars from a Hadoop image
        - name: add-s3a-jars
          image: apache/hadoop:3.3.6
          command: ["/bin/sh","-c"]
          args:
            - |
              set -eux
              mkdir -p /tools-lib
              cp -v /opt/hadoop/share/hadoop/tools/lib/hadoop-aws-*.jar /tools-lib/
              cp -v /opt/hadoop/share/hadoop/tools/lib/aws-*.jar /tools-lib/ || true
              cp -v /opt/hadoop/share/hadoop/tools/lib/*aws*sdk*.jar /tools-lib/ || true
          volumeMounts:
            - name: hadoop-tools-lib
              mountPath: /tools-lib
        # 2) Initialize the Hive schema BEFORE the metastore starts
        - name: init-hive-schema
          image: apache/hive:3.1.3
          command: ["/bin/sh","-c"]
          args:
            - >
              set -eux;
              # Ensure S3A libs are visible to Hadoop inside this container
              mkdir -p /opt/hadoop/share/hadoop/tools/lib &&
              cp -vn /hadoop-tools-lib/* /opt/hadoop/share/hadoop/tools/lib/ || true;
              # (Optional) warn if PostgreSQL JDBC jar is missing
              ls -1 /opt/hive/lib/postgresql*.jar || echo "WARN: PostgreSQL JDBC jar not found in image";
              # Initialize schema (idempotent if already created will fail gracefully)
              /opt/hive/bin/schematool -dbType postgres -initSchema -verbose || true
          volumeMounts:
            - name: hive-site
              mountPath: /opt/hive/conf/hive-site.xml
              subPath: hive-site.xml
            - name: hadoop-core-site
              mountPath: /opt/hadoop/etc/hadoop/core-site.xml
              subPath: core-site.xml
            - name: hadoop-tools-lib
              mountPath: /hadoop-tools-lib
      containers:
        - name: metastore
          image: apache/hive:3.1.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: thrift
              containerPort: 9083
          command: ["/bin/sh","-c"]
          args:
            - >
              set -eux;
              # Ensure S3A libs available at runtime as well
              mkdir -p /opt/hadoop/share/hadoop/tools/lib &&
              cp -vn /hadoop-tools-lib/* /opt/hadoop/share/hadoop/tools/lib/ || true;
              # Start Metastore
              /opt/hive/bin/hive --service metastore -p 9083
          readinessProbe:
            tcpSocket: { port: 9083 }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket: { port: 9083 }
            initialDelaySeconds: 20
            periodSeconds: 20
          volumeMounts:
            - name: hive-site
              mountPath: /opt/hive/conf/hive-site.xml
              subPath: hive-site.xml
            - name: hadoop-core-site
              mountPath: /opt/hadoop/etc/hadoop/core-site.xml
              subPath: core-site.xml
            - name: hadoop-tools-lib
              mountPath: /hadoop-tools-lib
      volumes:
        - name: hive-site
          configMap:
            name: hive-site
        - name: hadoop-core-site
          configMap:
            name: hadoop-core-site
        - name: hadoop-tools-lib
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: hive-metastore
spec:
  selector:
    app: hive-metastore
  ports:
    - name: thrift
      port: 9083
      targetPort: 9083
      protocol: TCP
