apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      initContainers:
        - name: fetch-deps
          image: curlimages/curl:8.2.1
          command:
            - sh
            - -c
            - |
              set -e
              mkdir -p /hive-lib
      
              echo "📥 Downloading Hive JARs..."
              curl -L -o /hive-lib/hive-cli-3.1.3.jar https://repo1.maven.org/maven2/org/apache/hive/hive-cli/3.1.3/hive-cli-3.1.3.jar
              curl -L -o /hive-lib/hive-exec-3.1.3.jar https://repo1.maven.org/maven2/org/apache/hive/hive-exec/3.1.3/hive-exec-3.1.3.jar
              curl -L -o /hive-lib/hive-metastore-3.1.3.jar https://repo1.maven.org/maven2/org/apache/hive/hive-metastore/3.1.3/hive-metastore-3.1.3.jar
              curl -L -o /hive-lib/hive-common-3.1.3.jar https://repo1.maven.org/maven2/org/apache/hive/hive-common/3.1.3/hive-common-3.1.3.jar
      
              echo "📥 Downloading Thrift and Facebook JARs..."
              curl -L -o /hive-lib/libfb303-0.9.3.jar https://repo1.maven.org/maven2/org/apache/thrift/libfb303/0.9.3/libfb303-0.9.3.jar
              curl -L -o /hive-lib/libthrift-0.9.3.jar https://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.9.3/libthrift-0.9.3.jar
      
              echo "📥 Downloading Log4j JARs..."
              curl -L -o /hive-lib/log4j-api-2.17.1.jar https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.jar
              curl -L -o /hive-lib/log4j-core-2.17.1.jar https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.17.1/log4j-core-2.17.1.jar
      
              echo "✅ All jars downloaded."
          volumeMounts:
            - name: shared-jars
              mountPath: /hive-lib

      containers:
        - name: metastore
          image: apache/hive:3.1.3
          command:
            - /bin/bash
            - -c
            - |
              echo "🔍 Checking if schema is already initialized..."
              if ! /opt/hive/bin/schematool -info -dbType postgres; then
                echo "📦 Initializing schema..."
                /opt/hive/bin/schematool -initSchema -dbType postgres -verbose
              else
                echo "✅ Schema already exists. Skipping."
              fi
              echo "🚀 Starting Hive Metastore..."
              /opt/hive/bin/hive --service metastore
          env:
            - name: HIVE_CONF_DIR
              value: /opt/hive/conf
          ports:
            - containerPort: 9083
          volumeMounts:
            - name: hive-conf
              mountPath: /opt/hive/conf/metastore-site.xml
              subPath: metastore-site.xml
            - name: hive-conf
              mountPath: /opt/hive/conf/hive-site.xml
              subPath: metastore-site.xml
            - name: shared-jars
              mountPath: /opt/hive/lib
      volumes:
        - name: hive-conf
          configMap:
            name: hive-metastore-site
        - name: shared-jars
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: hive-metastore
spec:
  selector:
    app: hive-metastore
  ports:
    - name: thrift
      port: 9083
      targetPort: 9083
