apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      initContainers:
        - name: fetch-deps
          image: curlimages/curl:8.2.1
          command:
            - sh
            - -c
            - |
               curl -L -o /jars/hive-exec-3.1.3.jar https://repo1.maven.org/maven2/org/apache/hive/hive-exec/3.1.3/hive-exec-3.1.3.jar
               curl -L -o /jars/hive-metastore-3.1.3.jar https://repo1.maven.org/maven2/org/apache/hive/hive-metastore/3.1.3/hive-metastore-3.1.3.jar
               curl -L -o /jars/hadoop-aws-3.3.6.jar https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.6/hadoop-aws-3.3.6.jar
               curl -L -o /jars/aws-java-sdk-bundle-1.11.1026.jar https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.1026/aws-java-sdk-bundle-1.11.1026.jar
          volumeMounts:
            - name: shared-jars
              mountPath: /jars

      containers:
        - name: metastore
          image: apache/hive:3.1.3
          command:
            - /bin/bash
            - -c
            - |
              echo "🔍 Checking if schema is already initialized..."
              if ! /opt/hive/bin/schematool -info -dbType postgres; then
                echo "📦 Initializing schema..."
                /opt/hive/bin/schematool -initSchema -dbType postgres -verbose
              else
                echo "✅ Schema already exists. Skipping."
              fi
              echo "🚀 Starting Hive Metastore..."
              /opt/hive/bin/hive --service metastore
          env:
            - name: HIVE_CONF_DIR
              value: /opt/hive/conf
          ports:
            - containerPort: 9083
          volumeMounts:
            - name: hive-conf
              mountPath: /opt/hive/conf/metastore-site.xml
              subPath: metastore-site.xml
            - name: hive-conf
              mountPath: /opt/hive/conf/hive-site.xml
              subPath: metastore-site.xml
            - name: shared-jars
              mountPath: /opt/hive/lib
      volumes:
        - name: hive-conf
          configMap:
            name: hive-metastore-site
        - name: shared-jars
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: hive-metastore
spec:
  selector:
    app: hive-metastore
  ports:
    - name: thrift
      port: 9083
      targetPort: 9083
