apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      initContainers:
        - name: schema-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - /bin/bash
            - -c
            - |
              echo "Checking if Hive schema exists..."
              SCHEMA_COUNT=$(PGPASSWORD={{ .Values.postgres.password }} psql -h {{ .Values.postgres.host }} -U {{ .Values.postgres.user }} -d {{ .Values.postgres.db }} -tAc "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='public';")
              if [ "$SCHEMA_COUNT" = "0" ]; then
                echo "Initializing Hive Metastore schema..."
                schematool -initSchema -dbType postgres
              else
                echo "Hive schema already exists. Skipping initialization."
              fi
          env:
            - name: PGPASSWORD
              value: {{ .Values.postgres.password }}
          volumeMounts:
            - name: hive-config
              mountPath: /opt/hive/conf
      containers:
        - name: metastore
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - /opt/hive/bin/hive
            - --service
            - metastore
          ports:
            - containerPort: {{ .Values.metastore.port }}
          volumeMounts:
            - name: hive-config
              mountPath: /opt/hive/conf
      volumes:
        - name: hive-config
          configMap:
            name: hive-site
---

apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
spec:
  selector:
    app: hive-metastore
  ports:
    - protocol: TCP
      port: {{ .Values.metastore.port }}
      targetPort: {{ .Values.metastore.port }}
