apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      initContainers:
        - name: copy-hadoop-aws
          image: apache/hadoop:3.3.6
          command:
            - sh
            - -c
            - |
              cp /opt/hadoop/share/hadoop/tools/lib/hadoop-aws-*.jar /hadoop-aws/ &&
              cp /opt/hadoop/share/hadoop/tools/lib/aws-java-sdk-bundle-*.jar /hadoop-aws/
          volumeMounts:
            - name: hadoop-aws-jars
              mountPath: /hadoop-aws
      containers:
        - name: metastore
          image: apache/hive:3.1.3
          command:
            - /bin/bash
            - -c
            - |
              echo "🔍 Checking if schema is already initialized..."
              if ! /opt/hive/bin/schematool -info -dbType postgres; then
                echo "📦 Initializing schema..."
                /opt/hive/bin/schematool -initSchema -dbType postgres -verbose
              else
                echo "✅ Schema already exists. Skipping."
              fi
              echo "🚀 Starting Hive Metastore..."
              /opt/hive/bin/hive --service metastore
          env:
            - name: HIVE_CONF_DIR
              value: /opt/hive/conf
          ports:
            - containerPort: 9083
          volumeMounts:
            - name: hive-conf
              mountPath: /opt/hive/conf/metastore-site.xml
              subPath: metastore-site.xml
            - name: hive-conf
              mountPath: /opt/hive/conf/hive-site.xml
              subPath: metastore-site.xml
            - name: hadoop-aws-jars
              mountPath: /opt/hive/lib
      volumes:
        - name: hive-conf
          configMap:
            name: hive-metastore-site
        - name: hadoop-aws-jars
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: hive-metastore
  ports:
    - name: thrift
      port: 9083
      targetPort: 9083
