apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
        - name: metastore
          image: apache/hive:3.1.3
          ports:
            - containerPort: 9083
          volumeMounts:
            - name: hive-metastore-site
              mountPath: /opt/hive/conf/metastore-site.xml
              subPath: metastore-site.xml
      volumes:
        - name: hive-metastore-site
          configMap:
            name: hive-metastore-site

---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: hive-metastore
spec:
  selector:
    app: hive-metastore
  ports:
    - name: thrift
      port: 9083
      targetPort: 9083
  type: ClusterIP

