apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
        - name: metastore
          image: apache/hive:3.1.3
          ports:
            - containerPort: 9083
          args:
            - "--service"
            - "metastore"
            - "-hiveconf"
            - "javax.jdo.option.ConnectionURL=jdbc:postgresql://postgresql.postgresql.svc.cluster.local:5432/hive_metastore"
            - "-hiveconf"
            - "javax.jdo.option.ConnectionDriverName=org.postgresql.Driver"
            - "-hiveconf"
            - "javax.jdo.option.ConnectionUserName=admin"
            - "-hiveconf"
            - "javax.jdo.option.ConnectionPassword=admin"
            - "-hiveconf"
            - "hive.metastore.warehouse.dir=s3a://testbuckettrino/testpathtrino"
            - "-hiveconf"
            - "fs.s3a.endpoint=http://minio.minio.svc.cluster.local:9000"
            - "-hiveconf"
            - "fs.s3a.path.style.access=true"
            - "-hiveconf"
            - "fs.s3a.connection.ssl.enabled=false"
            - "-hiveconf"
            - "fs.s3a.access.key=minioadmin"
            - "-hiveconf"
            - "fs.s3a.secret.key=minioadmin"

---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: hive-metastore
spec:
  selector:
    app: hive-metastore
  ports:
    - name: thrift
      port: 9083
      targetPort: 9083
  type: ClusterIP
