apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: vault
  serviceName: vault
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: [ "vault" ]
          args:
            - "server"
            - "-config=/vault/config/vault-config.hcl"
          ports:
            - containerPort: 8200
          volumeMounts:
            - name: vault-config
              mountPath: /vault/config
            - name: vault-data
              mountPath: /vault/file
      volumes:
        - name: vault-config
          configMap:
            name: vault-config
        - name: vault-data
          persistentVolumeClaim:
            claimName: vault-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
spec:
  type: ClusterIP
  ports:
    - port: 8200
      targetPort: 8200
      protocol: TCP
  selector:
    app: vault

---
{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: vault-ui
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.ui.serviceType }}
  ports:
    - port: 8200
      targetPort: 8200
      nodePort: {{ .Values.ui.nodePort }}
      protocol: TCP
      name: http
  selector:
    app: vault
{{- end }}

