image:
  repository: trinodb/trino
  tag: 476
  pullPolicy: IfNotPresent

hive:
  catalogName: hive
  metastoreUri: thrift://hive-metastore.hive-metastore.svc.cluster.local:9083
  s3:
    endpoint: http://minio.minio.svc.cluster.local:9000
    bucket: lakehouse
    accessKey: minioadmin
    secretKey: minioadmin
    sslEnabled: false
    pathStyleAccess: true
    warehouseDir: s3a://lakehouse/user/hive/warehouse  # not used but retained

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

service:
  type: ClusterIP
  port: 8080
